# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QLCDNumber, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QProgressBar,
    QSizePolicy, QStatusBar, QTextBrowser, QToolBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(640, 480)
        self.actionEdit = QAction(MainWindow)
        self.actionEdit.setObjectName(u"actionEdit")
        self.actionView = QAction(MainWindow)
        self.actionView.setObjectName(u"actionView")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionPrint = QAction(MainWindow)
        self.actionPrint.setObjectName(u"actionPrint")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionVideo = QAction(MainWindow)
        self.actionVideo.setObjectName(u"actionVideo")
        self.actionStill_Shots = QAction(MainWindow)
        self.actionStill_Shots.setObjectName(u"actionStill_Shots")
        self.actionConnect = QAction(MainWindow)
        self.actionConnect.setObjectName(u"actionConnect")
        self.actionDisconnect = QAction(MainWindow)
        self.actionDisconnect.setObjectName(u"actionDisconnect")
        self.actionReport = QAction(MainWindow)
        self.actionReport.setObjectName(u"actionReport")
        icon = QIcon()
        icon.addFile(u"stuffserial/gears.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionReport.setIcon(icon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(450, 350, 118, 23))
        self.progressBar.setValue(24)
        self.labelWowSerState = QLabel(self.centralwidget)
        self.labelWowSerState.setObjectName(u"labelWowSerState")
        self.labelWowSerState.setGeometry(QRect(450, 320, 121, 16))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(50, 40, 70, 16))
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(50, 60, 125, 21))
        self.lineEdit_2 = QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(50, 120, 125, 21))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(50, 100, 70, 16))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 170, 151, 16))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 10, 101, 16))
        self.lcdNumber_CoilAFreq = QLCDNumber(self.centralwidget)
        self.lcdNumber_CoilAFreq.setObjectName(u"lcdNumber_CoilAFreq")
        self.lcdNumber_CoilAFreq.setGeometry(QRect(240, 60, 109, 23))
        font = QFont()
        font.setFamilies([u"Academy Engraved LET"])
        self.lcdNumber_CoilAFreq.setFont(font)
        self.lcdNumber_CoilAFreq.setDigitCount(10)
        self.lcdNumber_CoilBFreq = QLCDNumber(self.centralwidget)
        self.lcdNumber_CoilBFreq.setObjectName(u"lcdNumber_CoilBFreq")
        self.lcdNumber_CoilBFreq.setGeometry(QRect(240, 120, 109, 23))
        self.lcdNumber_CoilBFreq.setFont(font)
        self.lcdNumber_CoilBFreq.setDigitCount(10)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(50, 209, 131, 21))
        self.lcdNumber_CoilATemp = QLCDNumber(self.centralwidget)
        self.lcdNumber_CoilATemp.setObjectName(u"lcdNumber_CoilATemp")
        self.lcdNumber_CoilATemp.setGeometry(QRect(240, 209, 111, 23))
        self.lcdNumber_CoilATemp.setDigitCount(10)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(50, 250, 131, 21))
        self.lcdNumber_CoilBTemp = QLCDNumber(self.centralwidget)
        self.lcdNumber_CoilBTemp.setObjectName(u"lcdNumber_CoilBTemp")
        self.lcdNumber_CoilBTemp.setGeometry(QRect(240, 250, 111, 23))
        self.lcdNumber_CoilBTemp.setDigitCount(10)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 300, 151, 16))
        self.textBrowser_MainWindow = QTextBrowser(self.centralwidget)
        self.textBrowser_MainWindow.setObjectName(u"textBrowser_MainWindow")
        self.textBrowser_MainWindow.setGeometry(QRect(50, 320, 381, 51))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 640, 24))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuSerial = QMenu(self.menubar)
        self.menuSerial.setObjectName(u"menuSerial")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSerial.menuAction())
        self.menuFile.addAction(self.actionEdit)
        self.menuFile.addAction(self.actionView)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuView.addAction(self.actionVideo)
        self.menuView.addAction(self.actionStill_Shots)
        self.menuSerial.addAction(self.actionConnect)
        self.menuSerial.addAction(self.actionDisconnect)
        self.menuSerial.addSeparator()
        self.menuSerial.addAction(self.actionReport)
        self.toolBar.addAction(self.actionReport)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Twin Device", None))
#if QT_CONFIG(tooltip)
        MainWindow.setToolTip(QCoreApplication.translate("MainWindow", u"Copyright (C) 2024 Wild Rose Technologies Inc.", None))
#endif // QT_CONFIG(tooltip)
        self.actionEdit.setText(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.actionView.setText(QCoreApplication.translate("MainWindow", u"View", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionPrint.setText(QCoreApplication.translate("MainWindow", u"Print", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionVideo.setText(QCoreApplication.translate("MainWindow", u"Video", None))
        self.actionStill_Shots.setText(QCoreApplication.translate("MainWindow", u"Still Shots", None))
        self.actionConnect.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.actionDisconnect.setText(QCoreApplication.translate("MainWindow", u"Disconnect", None))
        self.actionReport.setText(QCoreApplication.translate("MainWindow", u"Report", None))
#if QT_CONFIG(tooltip)
        self.progressBar.setToolTip(QCoreApplication.translate("MainWindow", u"Driving the device...", None))
#endif // QT_CONFIG(tooltip)
        self.labelWowSerState.setText(QCoreApplication.translate("MainWindow", u"WowSer", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Coil A", None))
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Set frequency...", None))
        self.lineEdit_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Set frequency...", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Coil B", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Sensors and Monitoring</span></p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">Coil Settings</span></p></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Temperature Coil A", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Temperature Coil B", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:700;\">State of Driving</span></p></body></html>", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuSerial.setTitle(QCoreApplication.translate("MainWindow", u"Serial", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

